"""RAG Retrieval package alias re-exporting from retrieval."""

from retrieval import (
    AdaptiveTransformationPolicy,
    BaseLLMClient,
    BaseTransformationPolicy,
    BaseTransformationStrategy,
    EmptyQueryError,
    InvalidQueryError,
    LLMQueryRewriteStrategy,
    OpenAICompatibleLLMClient,
    PolicyDecision,
    ProcessedQuery,
    QueryLengthExceededError,
    QueryPreprocessingConfig,
    QueryPreprocessingError,
    QueryPreprocessingService,
    QueryPreprocessor,
    QueryTransformationConfig,
    QueryTransformationService,
    RetrievalError,
    RetrievalQuerySet,
    TransformationFallbackLimitExceededError,
    TransformationOutputValidator,
    TransformationProviderError,
    TransformationTimeoutError,
    TransformationUnavailableError,
    TransformationValidationError,
    ValidationResult,
    get_query_preprocessor,
    get_query_transformation_service,
    preprocess_query,
    reset_query_preprocessor,
    reset_query_transformation_service,
    transform_query,
)

__all__ = [
    # Domain Models
    "ProcessedQuery",
    "PolicyDecision",
    "RetrievalQuerySet",
    # Configuration
    "QueryPreprocessingConfig",
    "QueryTransformationConfig",
    # Preprocessing
    "QueryPreprocessor",
    "QueryPreprocessingService",
    "get_query_preprocessor",
    "reset_query_preprocessor",
    "preprocess_query",
    # Transformation Subsystem & Helpers
    "QueryTransformationService",
    "get_query_transformation_service",
    "reset_query_transformation_service",
    "transform_query",
    "BaseTransformationPolicy",
    "AdaptiveTransformationPolicy",
    "BaseTransformationStrategy",
    "LLMQueryRewriteStrategy",
    "BaseLLMClient",
    "OpenAICompatibleLLMClient",
    "TransformationOutputValidator",
    "ValidationResult",
    # Domain Exceptions
    "RetrievalError",
    "QueryPreprocessingError",
    "InvalidQueryError",
    "EmptyQueryError",
    "QueryLengthExceededError",
    "QueryTransformationError",
    "TransformationValidationError",
    "TransformationProviderError",
    "TransformationTimeoutError",
    "TransformationUnavailableError",
    "TransformationFallbackLimitExceededError",
]

