"""RAG Retrieval package alias re-exporting from retrieval."""

from retrieval import (
    AdaptiveTransformationPolicy,
    BaseLLMClient,
    BaseTransformationPolicy,
    BaseTransformationStrategy,
    EmbeddedQuery,
    EmbeddedQuerySet,
    EmptyQueryError,
    InvalidQueryError,
    LLMQueryRewriteStrategy,
    OpenAICompatibleLLMClient,
    PolicyDecision,
    ProcessedQuery,
    QueryEmbeddingError,
    QueryEmbeddingService,
    QueryLengthExceededError,
    QueryPreprocessingConfig,
    QueryPreprocessingError,
    QueryPreprocessingService,
    QueryPreprocessor,
    QueryTransformationConfig,
    QueryTransformationService,
    RetrievalError,
    RetrievalQuerySet,
    TransformationFallbackLimitExceededError,
    TransformationOutputValidator,
    TransformationProviderError,
    TransformationTimeoutError,
    TransformationUnavailableError,
    TransformationValidationError,
    ValidationResult,
    VectorRetrievalError,
    VectorSearchCandidate,
    VectorSearchConfig,
    VectorSearchService,
    embed_query_set,
    get_query_embedding_service,
    get_query_preprocessor,
    get_query_transformation_service,
    get_vector_search_service,
    preprocess_query,
    reset_query_embedding_service,
    reset_query_preprocessor,
    reset_query_transformation_service,
    reset_vector_search_service,
    search_vectors,
    transform_query,
)

__all__ = [
    # Domain Models
    "ProcessedQuery",
    "PolicyDecision",
    "RetrievalQuerySet",
    "EmbeddedQuery",
    "EmbeddedQuerySet",
    "VectorSearchCandidate",
    # Configuration
    "QueryPreprocessingConfig",
    "QueryTransformationConfig",
    "VectorSearchConfig",
    # Preprocessing
    "QueryPreprocessor",
    "QueryPreprocessingService",
    "get_query_preprocessor",
    "reset_query_preprocessor",
    "preprocess_query",
    # Transformation Subsystem & Helpers
    "QueryTransformationService",
    "get_query_transformation_service",
    "reset_query_transformation_service",
    "transform_query",
    "BaseTransformationPolicy",
    "AdaptiveTransformationPolicy",
    "BaseTransformationStrategy",
    "LLMQueryRewriteStrategy",
    "BaseLLMClient",
    "OpenAICompatibleLLMClient",
    "TransformationOutputValidator",
    "ValidationResult",
    # Query Embedding Subsystem & Helpers
    "QueryEmbeddingService",
    "get_query_embedding_service",
    "reset_query_embedding_service",
    "embed_query_set",
    # Vector Search Subsystem & Helpers
    "VectorSearchService",
    "get_vector_search_service",
    "reset_vector_search_service",
    "search_vectors",
    # Domain Exceptions
    "RetrievalError",
    "QueryPreprocessingError",
    "InvalidQueryError",
    "EmptyQueryError",
    "QueryLengthExceededError",
    "QueryTransformationError",
    "TransformationValidationError",
    "TransformationProviderError",
    "TransformationTimeoutError",
    "TransformationUnavailableError",
    "TransformationFallbackLimitExceededError",
    "QueryEmbeddingError",
    "VectorRetrievalError",
]

