"""BRD Rewriter Sub-Agent implementation.

Provides the dedicated, specialized document correction execution capability
for the BRD Agent architecture. Executes targeted document modifications strictly
as specified by the Final Validation Sub-Agent with minimum necessary document change.

Strict Architectural Boundaries:
- Final Validation owns diagnosis (what is wrong, where it is, and why).
- BRD Rewriter owns execution (applying the specified correction minimally).
- Rewriter has NO tools (tools=[]: cannot call RAG, access databases, or invoke external tools).
- Rewriter does not independently search, reinterpret, or reassess project evidence.
- Rewriter modifies only the content specified by findings, preserving all untouched text.
- Rewriter never returns to Section Validation or re-evaluates section-level gates.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import json
from pathlib import Path
import re
import time
from typing import Any, Optional, Sequence

from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import HumanMessage

from agents.brd.config import AgentConfig, create_agent_model
from agents.brd.final_validation.agent import FinalValidationFinding
from deepagents import create_deep_agent
from observability import (
    execute_with_rate_limit_retry_async,
    extract_rate_limit_info,
    get_logger,
)

logger = get_logger(__name__)

SYSTEM_INSTRUCTION_FILE = "system_instruction.md"


def get_rewriter_system_instruction_path() -> Path:
    """Resolve the absolute path to the BRD Rewriter system instruction Markdown file."""
    return Path(__file__).resolve().parent / SYSTEM_INSTRUCTION_FILE


def load_rewriter_system_instruction() -> str:
    """Load the authoritative BRD Rewriter system instruction from Markdown.

    Returns:
        str: Content of the system instruction.

    Raises:
        FileNotFoundError: If the system instruction Markdown file does not exist.
        ValueError: If the system instruction Markdown file is empty.
    """
    path = get_rewriter_system_instruction_path()
    if not path.is_file():
        raise FileNotFoundError(
            f"Required rewriter system instruction file not found: {path}"
        )

    try:
        content = path.read_text(encoding="utf-8").strip()
    except Exception as exc:
        logger.error("Failed to read rewriter system instruction from %s: %s", path, exc)
        raise

    if not content:
        raise ValueError(f"Rewriter system instruction file is empty: {path}")

    return content


@dataclass
class DocumentEdit:
    """Targeted text replacement generated by BRDRewriterAgent.

    Attributes:
        finding_id: Identifier of the FinalValidationFinding addressed (e.g. 'FV-001').
        target_location: Heading or subsection location (e.g. 'Section 6.2').
        original_fragment: Exact verbatim substring from the current BRD to replace.
        corrected_fragment: Exact replacement text implementing the specified correction.
        explanation: Brief explanation of the targeted edit.
    """

    finding_id: str
    target_location: str
    original_fragment: str
    corrected_fragment: str
    explanation: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Serialize edit to dictionary."""
        return {
            "finding_id": self.finding_id,
            "target_location": self.target_location,
            "original_fragment": self.original_fragment,
            "corrected_fragment": self.corrected_fragment,
            "explanation": self.explanation,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "DocumentEdit":
        """Deserialize dictionary into a DocumentEdit."""
        return cls(
            finding_id=str(data.get("finding_id", "")),
            target_location=str(data.get("target_location", "")),
            original_fragment=str(data.get("original_fragment", "")),
            corrected_fragment=str(data.get("corrected_fragment", "")),
            explanation=str(data.get("explanation", "")),
        )


@dataclass
class BRDRewriterContext:
    """Scoped context provided as input to the BRD Rewriter Sub-Agent.

    Attributes:
        assembled_document: Complete Markdown text of the assembled BRD.
        findings: All FinalValidationFinding items produced by Final Validation.
        finding_evidence: Specific evidence items attached to or referenced by findings.
        metadata: Execution metadata (e.g. project_id, agent_run_id).
    """

    assembled_document: str
    findings: list[FinalValidationFinding] = field(default_factory=list)
    finding_evidence: list[dict[str, str]] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialize context to dictionary."""
        return {
            "assembled_document": self.assembled_document,
            "findings": [f.to_dict() if hasattr(f, "to_dict") else f for f in self.findings],
            "finding_evidence": list(self.finding_evidence),
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "BRDRewriterContext":
        """Deserialize dictionary into a BRDRewriterContext."""
        raw_findings = data.get("findings", [])
        findings = [
            FinalValidationFinding.from_dict(f) if isinstance(f, dict) else f
            for f in raw_findings
        ]
        return cls(
            assembled_document=str(data.get("assembled_document", "")),
            findings=findings,
            finding_evidence=list(data.get("finding_evidence", [])),
            metadata=dict(data.get("metadata", {})),
        )


@dataclass
class BRDRewriterResult:
    """Structured result returned by BRDRewriterAgent.

    Attributes:
        edits: Ordered list of targeted DocumentEdit modifications.
        unapplied_findings: Finding IDs that could not be safely resolved via edit
            (e.g. open questions or missing evidence).
        summary: Concise summary of targeted modifications applied.
        metadata: Execution metrics (duration, edit count, etc.).
    """

    edits: list[DocumentEdit] = field(default_factory=list)
    unapplied_findings: list[str] = field(default_factory=list)
    summary: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialize result to dictionary."""
        return {
            "summary": self.summary,
            "edits": [e.to_dict() if hasattr(e, "to_dict") else e for e in self.edits],
            "unapplied_findings": list(self.unapplied_findings),
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "BRDRewriterResult":
        """Deserialize dictionary into a BRDRewriterResult."""
        raw_edits = data.get("edits", [])
        edits = [
            DocumentEdit.from_dict(e) if isinstance(e, dict) else e
            for e in raw_edits
        ]
        return cls(
            edits=edits,
            unapplied_findings=list(data.get("unapplied_findings", [])),
            summary=str(data.get("summary", "")),
            metadata=dict(data.get("metadata", {})),
        )


def _build_rewriter_prompt(context: BRDRewriterContext) -> str:
    """Format prompt with focused context for the BRD Rewriter Sub-Agent."""
    parts: list[str] = [
        "## Document Rewriting Task\n"
        "Execute the corrections specified by Final Validation on the complete assembled Business Requirements Document (BRD).\n"
        "Apply the specified corrections with the MINIMUM NECESSARY DOCUMENT CHANGE.\n"
        "Preserve all content outside the explicitly targeted corrections, except for unavoidable formatting changes directly resulting from applying those corrections.",
    ]

    # Format findings and referenced evidence
    findings_lines: list[str] = []
    for idx, f in enumerate(context.findings, start=1):
        f_id = f.finding_id or f"FV-{idx:03d}"
        cat = f.category.value if hasattr(f.category, "value") else str(f.category)
        loc = f.location or (", ".join(f.affected_sections) if f.affected_sections else "Document-wide")
        status = f.resolution_status.value if hasattr(f.resolution_status, "value") else str(f.resolution_status)

        findings_lines.append(f"### Finding {idx}: [{f_id}] {f.issue} (Category: {cat}, Status: {status})")
        findings_lines.append(f"- Location: {loc}")
        if f.problematic_content:
            findings_lines.append(f"- Problematic / Conflicting Content:\n  ```text\n  {f.problematic_content}\n  ```")
        if f.explanation:
            findings_lines.append(f"- Why this is a defect: {f.explanation}")
        if f.evidence:
            findings_lines.append(f"- Attached Project Evidence:\n  > {f.evidence}")
        corr = f.required_correction or f.required_change
        if corr:
            findings_lines.append(f"- Required Correction Instruction: {corr}")
        if f.intended_outcome:
            findings_lines.append(f"- Intended Outcome: {f.intended_outcome}")
        if f.open_question:
            findings_lines.append(f"- Open Question (Requires Stakeholder Clarification): {f.open_question}")
        findings_lines.append("")

    parts.append("## Final Validation Findings to Address\n" + "\n".join(findings_lines))

    if context.finding_evidence:
        ev_lines = []
        for item in context.finding_evidence:
            src = item.get("source", "project_evidence")
            content = item.get("content", str(item))
            ev_lines.append(f"**Source: {src}**\n{content}\n")
        parts.append("## Referenced Finding Evidence\n" + "\n".join(ev_lines))

    parts.append(
        f"## Complete Assembled BRD Document (Base for Edits)\n```markdown\n{context.assembled_document.strip()}\n```"
    )

    parts.append(
        "Instructions for Generating Targeted Edits:\n"
        "1. For each actionable finding with an evidence-backed correction instruction, generate a DocumentEdit.\n"
        "2. In each edit, provide `original_fragment` with enough verbatim surrounding context from the BRD so it is uniquely locatable.\n"
        "3. Provide `corrected_fragment` containing the replacement text implementing the specified correction.\n"
        "4. If a finding is marked OPEN_QUESTION or lacks sufficient evidence to resolve safely, do NOT invent a business decision. Add its finding_id to `unapplied_findings`.\n"
        "5. Coordinate all edits together so they are mutually consistent.\n"
        "6. Return ONLY a valid JSON object matching the output schema."
    )

    return "\n\n".join(parts)


def _parse_rewriter_response(
    response_text: str,
    context: BRDRewriterContext,
    duration: float = 0.0,
) -> BRDRewriterResult:
    """Parse LLM output text into structured BRDRewriterResult, with robust JSON extraction."""
    json_match = re.search(r"\{\s*\"summary\".*\}\s*", response_text, re.DOTALL)
    if not json_match:
        json_match = re.search(r"\{\s*\"edits\".*\}\s*", response_text, re.DOTALL)
    if not json_match:
        json_match = re.search(r"\{.*\}", response_text, re.DOTALL)

    if json_match:
        raw_json = json_match.group(0)
        try:
            parsed = json.loads(raw_json)
            if isinstance(parsed, dict):
                summary = str(parsed.get("summary", "")).strip()
                raw_edits = parsed.get("edits", [])
                edits: list[DocumentEdit] = []
                if isinstance(raw_edits, list):
                    for item in raw_edits:
                        if isinstance(item, dict):
                            edits.append(DocumentEdit.from_dict(item))

                unapplied = [str(u) for u in parsed.get("unapplied_findings", [])]

                return BRDRewriterResult(
                    edits=edits,
                    unapplied_findings=unapplied,
                    summary=summary or f"Applied {len(edits)} targeted document edits.",
                    metadata={
                        "duration_seconds": duration,
                        "edit_count": len(edits),
                    },
                )
        except Exception as exc:
            logger.warning("Failed to parse extracted JSON in rewriter response: %s", exc)

    logger.warning("BRDRewriter returned unstructured response; no targeted edits parsed.")
    # Safe fallback: treat all findings as unapplied
    unapplied_ids = [
        f.finding_id or f"FV-{idx:03d}"
        for idx, f in enumerate(context.findings, start=1)
    ]
    return BRDRewriterResult(
        edits=[],
        unapplied_findings=unapplied_ids,
        summary="No targeted edits could be extracted from rewriter response.",
        metadata={
            "duration_seconds": duration,
            "fallback_parsing": True,
        },
    )


class BRDRewriterAgent:
    """Dedicated, reusable BRD Rewriter Sub-Agent capability.

    Executes targeted document modifications specified by Final Validation on the complete
    assembled BRD with minimum necessary document change.

    Architectural Invariants:
    1. Operates strictly as a modification execution capability; never reviews or diagnoses.
    2. Equipped with NO tools (tools=[]); cannot call RAG, query databases, or fetch data.
    3. Does not receive raw project evidence; only evidence attached to or referenced by findings.
    4. Preserves all untouched text except for unavoidable formatting changes from applied edits.
    5. Returns structured DocumentEdit items for deterministic application by the Lead Agent.
    """

    agent_name: str = "BRDRewriterAgent"

    def __init__(
        self,
        model: Optional[BaseChatModel] = None,
        config: Optional[AgentConfig] = None,
        system_instruction: Optional[str] = None,
    ) -> None:
        """Initialize the BRD Rewriter Sub-Agent.

        Args:
            model: Optional pre-configured BaseChatModel instance.
            config: Optional AgentConfig instance. Used if model is omitted.
            system_instruction: Optional system instruction override.
        """
        self._system_instruction = system_instruction or load_rewriter_system_instruction()
        if model:
            self._model = model
        else:
            import dataclasses
            cfg = config or AgentConfig.from_settings()
            if cfg.max_tokens is None or cfg.max_tokens < 4000:
                cfg = dataclasses.replace(cfg, max_tokens=4000)
            self._model = create_agent_model(cfg)

        self._tools: list[Any] = []
        self._graph = create_deep_agent(
            model=self._model,
            tools=self._tools,
            system_prompt=self._system_instruction,
        )

    @property
    def system_instruction(self) -> str:
        """Return the authoritative rewriter system instruction."""
        return self._system_instruction

    @property
    def model(self) -> BaseChatModel:
        """Return the active language model."""
        return self._model

    @property
    def tools(self) -> list[Any]:
        """Return the list of active tools (always empty for Rewriter Sub-Agent)."""
        return self._tools

    @property
    def graph(self) -> Any:
        """Return the underlying DeepAgents execution graph."""
        return self._graph

    def rewrite(
        self,
        context: BRDRewriterContext | dict[str, Any],
    ) -> BRDRewriterResult:
        """Execute targeted document rewriting synchronously.

        Args:
            context: Scoped BRDRewriterContext or dictionary.

        Returns:
            BRDRewriterResult: Structured result with targeted edits.
        """
        ctx = BRDRewriterContext.from_dict(context) if isinstance(context, dict) else context

        start_time = time.perf_counter()
        logger.info(
            "BRD document rewriting started (document_length: %d, findings_count: %d)",
            len(ctx.assembled_document),
            len(ctx.findings),
        )

        try:
            prompt_input = _build_rewriter_prompt(ctx)
            result = self._graph.invoke({"messages": [HumanMessage(content=prompt_input)]})
            duration = time.perf_counter() - start_time

            messages = result.get("messages", [])
            output_text = ""
            if messages:
                last_msg = messages[-1]
                content = getattr(last_msg, "content", "")
                if isinstance(content, str):
                    output_text = content
                elif isinstance(content, list):
                    text_parts = [
                        p.get("text", "") if isinstance(p, dict) else str(p)
                        for p in content
                    ]
                    output_text = "".join(text_parts)
                else:
                    output_text = str(content)

            rewrite_res = _parse_rewriter_response(output_text, ctx, duration=duration)
            logger.info(
                "BRD document rewriting completed (edits: %d, unapplied: %d, duration: %.2fs)",
                len(rewrite_res.edits),
                len(rewrite_res.unapplied_findings),
                duration,
            )
            return rewrite_res

        except Exception as exc:
            duration = time.perf_counter() - start_time
            err_msg = str(exc).strip() or exc.__class__.__name__
            logger.error(
                "BRD Rewriter Sub-Agent execution failed (duration: %.2fs): %s",
                duration,
                err_msg,
                exc_info=True,
            )
            unapplied = [f.finding_id or f"FV-{i:03d}" for i, f in enumerate(ctx.findings, start=1)]
            return BRDRewriterResult(
                edits=[],
                unapplied_findings=unapplied,
                summary=f"Rewriter execution failed due to runtime error: {err_msg}",
                metadata={"error": err_msg, "duration_seconds": duration},
            )

    async def rewrite_async(
        self,
        context: BRDRewriterContext | dict[str, Any],
    ) -> BRDRewriterResult:
        """Execute targeted document rewriting asynchronously.

        Args:
            context: Scoped BRDRewriterContext or dictionary.

        Returns:
            BRDRewriterResult: Structured result with targeted edits.
        """
        ctx = BRDRewriterContext.from_dict(context) if isinstance(context, dict) else context

        start_time = time.perf_counter()
        logger.info(
            "Async BRD document rewriting started (document_length: %d, findings_count: %d)",
            len(ctx.assembled_document),
            len(ctx.findings),
        )

        try:
            prompt_input = _build_rewriter_prompt(ctx)
            result = await execute_with_rate_limit_retry_async(
                lambda: self._graph.ainvoke({"messages": [HumanMessage(content=prompt_input)]}),
                operation_name="rewrite_brd_document",
            )
            duration = time.perf_counter() - start_time

            messages = result.get("messages", [])
            output_text = ""
            if messages:
                last_msg = messages[-1]
                content = getattr(last_msg, "content", "")
                if isinstance(content, str):
                    output_text = content
                elif isinstance(content, list):
                    text_parts = [
                        p.get("text", "") if isinstance(p, dict) else str(p)
                        for p in content
                    ]
                    output_text = "".join(text_parts)
                else:
                    output_text = str(content)

            rewrite_res = _parse_rewriter_response(output_text, ctx, duration=duration)
            logger.info(
                "Async BRD document rewriting completed (edits: %d, unapplied: %d, duration: %.2fs)",
                len(rewrite_res.edits),
                len(rewrite_res.unapplied_findings),
                duration,
            )
            return rewrite_res

        except Exception as exc:
            duration = time.perf_counter() - start_time
            err_msg = str(exc).strip() or exc.__class__.__name__
            rate_info = extract_rate_limit_info(exc)
            logger.error(
                "Async BRD Rewriter Sub-Agent execution failed (duration: %.2fs, is_rate_limit: %s): %s",
                duration,
                rate_info.is_rate_limit,
                err_msg,
                exc_info=True,
            )
            unapplied = [f.finding_id or f"FV-{i:03d}" for i, f in enumerate(ctx.findings, start=1)]
            return BRDRewriterResult(
                edits=[],
                unapplied_findings=unapplied,
                summary=f"Rewriter execution failed due to runtime error: {err_msg}",
                metadata={
                    "error": err_msg,
                    "duration_seconds": duration,
                    "rate_limit_info": rate_info.to_dict() if rate_info.is_rate_limit else None,
                },
            )
