"""Retrieval package encompassing preprocessing and query transformation.

Serves the first stages of the Retrieval pipeline:
User Query -> Query Preprocessing -> Query Transformation -> Retrieval Query Set -> Retrieval
"""

from exceptions.retrieval import (
    EmptyQueryError,
    InvalidQueryError,
    QueryEmbeddingError,
    QueryLengthExceededError,
    QueryPreprocessingError,
    QueryTransformationError,
    RetrievalError,
    TransformationFallbackLimitExceededError,
    TransformationProviderError,
    TransformationTimeoutError,
    TransformationUnavailableError,
    TransformationValidationError,
    VectorRetrievalError,
    KeywordRetrievalError,
    SparseEncodingError,
    FusionError,
    MetadataFilteringError,
    InvalidFilterError,
    FilterEvaluationError,
    RerankingError,
    RerankingConfigurationError,
    RerankingValidationError,
    RerankingProviderError,
    RerankingTimeoutError,
    ChunkHydrationError,
    ChunkHydrationValidationError,
    ChunkNotFoundError,
    DatabaseRetrievalError,
    ProjectBoundaryViolationError,
)
from retrieval.config import (
    FusionConfig,
    KeywordSearchConfig,
    MetadataFilteringConfig,
    QueryPreprocessingConfig,
    QueryTransformationConfig,
    RerankingConfig,
    VectorSearchConfig,
)
from retrieval.hydration import (
    BaseChunkRepository,
    ChunkHydrationConfig,
    ChunkHydrationService,
    SQLAlchemyChunkRepository,
    get_chunk_hydration_service,
    get_chunk_repository,
    hydrate_candidates,
    reset_chunk_hydration_service,
    reset_chunk_repository,
)
from retrieval.filtering import (
    BaseFilterCondition,
    BooleanCondition,
    CandidateMetadataResolver,
    ComparisonOperator,
    CompoundCondition,
    ExactMatchCondition,
    LogicalOperator,
    MetadataConditionEvaluator,
    MetadataFilter,
    MetadataFilteringService,
    RangeCondition,
    SetCondition,
    filter_candidates,
    get_metadata_filtering_service,
    reset_metadata_filtering_service,
    to_qdrant_condition,
    to_qdrant_filter,
)
from retrieval.fusion import (
    BaseFusionStrategy,
    FusionService,
    ReciprocalRankFusionStrategy,
    fuse_results,
    get_fusion_service,
    reset_fusion_service,
)
from retrieval.reranking import (
    BaseReranker,
    RerankingService,
    ScoredDocument,
    VoyageReranker,
    get_reranking_service,
    rerank_candidates,
    reset_reranking_service,
    resolve_candidate_text,
)
from retrieval.embedding import (
    QueryEmbeddingService,
    embed_query_set,
    get_query_embedding_service,
    reset_query_embedding_service,
)
from retrieval.keyword import (
    BaseSparseEncoder,
    KeywordSearchService,
    TechnicalSparseEncoder,
    get_keyword_search_service,
    get_sparse_encoder,
    reset_keyword_search_service,
    reset_sparse_encoder,
    search_keywords,
)
from retrieval.models import (
    EmbeddedQuery,
    EmbeddedQuerySet,
    FusedCandidate,
    FusedSearchCandidate,
    KeywordSearchCandidate,
    PolicyDecision,
    ProcessedQuery,
    RerankedCandidate,
    RerankedSearchCandidate,
    HydratedCandidate,
    HydratedSearchCandidate,
    HydratedChunk,
    RetrievalQuerySet,
    SparseVector,
    VectorSearchCandidate,
)
from retrieval.preprocessing import (
    QueryPreprocessingService,
    QueryPreprocessor,
    get_query_preprocessor,
    preprocess_query,
    reset_query_preprocessor,
)
from retrieval.transformation import (
    AdaptiveTransformationPolicy,
    BaseLLMClient,
    BaseTransformationPolicy,
    BaseTransformationStrategy,
    LLMQueryRewriteStrategy,
    OpenAICompatibleLLMClient,
    QueryTransformationService,
    TransformationOutputValidator,
    ValidationResult,
    get_query_transformation_service,
    reset_query_transformation_service,
    transform_query,
)
from retrieval.vector import (
    VectorSearchService,
    get_vector_search_service,
    reset_vector_search_service,
    search_vectors,
)

__all__ = [
    # Domain Models
    "ProcessedQuery",
    "PolicyDecision",
    "RetrievalQuerySet",
    "EmbeddedQuery",
    "EmbeddedQuerySet",
    "VectorSearchCandidate",
    "SparseVector",
    "KeywordSearchCandidate",
    "FusedCandidate",
    "FusedSearchCandidate",
    "RerankedCandidate",
    "RerankedSearchCandidate",
    "HydratedCandidate",
    "HydratedSearchCandidate",
    "HydratedChunk",
    # Configuration
    "QueryPreprocessingConfig",
    "QueryTransformationConfig",
    "VectorSearchConfig",
    "KeywordSearchConfig",
    "FusionConfig",
    "RerankingConfig",
    "ChunkHydrationConfig",
    # Preprocessing Service & Helpers
    "QueryPreprocessor",
    "QueryPreprocessingService",
    "get_query_preprocessor",
    "reset_query_preprocessor",
    "preprocess_query",
    # Transformation Subsystem & Helpers
    "QueryTransformationService",
    "get_query_transformation_service",
    "reset_query_transformation_service",
    "transform_query",
    "BaseTransformationPolicy",
    "AdaptiveTransformationPolicy",
    "BaseTransformationStrategy",
    "LLMQueryRewriteStrategy",
    "BaseLLMClient",
    "OpenAICompatibleLLMClient",
    "TransformationOutputValidator",
    "ValidationResult",
    # Query Embedding Subsystem & Helpers
    "QueryEmbeddingService",
    "get_query_embedding_service",
    "reset_query_embedding_service",
    "embed_query_set",
    # Vector Search Subsystem & Helpers
    "VectorSearchService",
    "get_vector_search_service",
    "reset_vector_search_service",
    "search_vectors",
    # Keyword Search Subsystem & Helpers
    "KeywordSearchService",
    "get_keyword_search_service",
    "reset_keyword_search_service",
    "search_keywords",
    "BaseSparseEncoder",
    "TechnicalSparseEncoder",
    "get_sparse_encoder",
    "reset_sparse_encoder",
    # Fusion Subsystem & Helpers
    "FusionService",
    "get_fusion_service",
    "reset_fusion_service",
    "fuse_results",
    "BaseFusionStrategy",
    "ReciprocalRankFusionStrategy",
    # Metadata Filtering Subsystem & Helpers
    "MetadataFilteringConfig",
    "BaseFilterCondition",
    "ExactMatchCondition",
    "SetCondition",
    "RangeCondition",
    "BooleanCondition",
    "CompoundCondition",
    "MetadataFilter",
    "ComparisonOperator",
    "LogicalOperator",
    "MetadataConditionEvaluator",
    "CandidateMetadataResolver",
    "MetadataFilteringService",
    "get_metadata_filtering_service",
    "reset_metadata_filtering_service",
    "filter_candidates",
    "to_qdrant_condition",
    "to_qdrant_filter",
    # Reranking Subsystem & Helpers
    "BaseReranker",
    "ScoredDocument",
    "VoyageReranker",
    "RerankingService",
    "get_reranking_service",
    "reset_reranking_service",
    "rerank_candidates",
    "resolve_candidate_text",
    # Chunk Hydration Subsystem & Helpers
    "BaseChunkRepository",
    "SQLAlchemyChunkRepository",
    "get_chunk_repository",
    "reset_chunk_repository",
    "ChunkHydrationService",
    "get_chunk_hydration_service",
    "reset_chunk_hydration_service",
    "hydrate_candidates",
    # Domain Exceptions
    "RetrievalError",
    "QueryPreprocessingError",
    "InvalidQueryError",
    "EmptyQueryError",
    "QueryLengthExceededError",
    "QueryTransformationError",
    "TransformationValidationError",
    "TransformationProviderError",
    "TransformationTimeoutError",
    "TransformationUnavailableError",
    "TransformationFallbackLimitExceededError",
    "QueryEmbeddingError",
    "VectorRetrievalError",
    "KeywordRetrievalError",
    "SparseEncodingError",
    "FusionError",
    "MetadataFilteringError",
    "InvalidFilterError",
    "FilterEvaluationError",
    "RerankingError",
    "RerankingConfigurationError",
    "RerankingValidationError",
    "RerankingProviderError",
    "RerankingTimeoutError",
    "ChunkHydrationError",
    "ChunkHydrationValidationError",
    "ChunkNotFoundError",
    "DatabaseRetrievalError",
    "ProjectBoundaryViolationError",
]

